### ISSUE TITLE
can u check me with this dependency issue

### ISSUE THREAD

**Issue by sindujarajan** [Cillian-Collins/subscraper#7]
Traceback (most recent call last):
  File "subscraper.py", line 8, in <module>
    from Color_Console import ctext
  File "/usr/local/lib/python2.7/dist-packages/Color_Console/__init__.py", line 1, in <module>
    from Color_Console.Color_Console import *
  File "/usr/local/lib/python2.7/dist-packages/Color_Console/Color_Console.py", line 190
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/dist-packages/Color_Console/Color_Console.py on line 191, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by Cillian-Collins** [comment]
This is a python 3 project and you are running it in python 2 so it throws an error.
